### ISSUE TITLE
hint: does not work with neovim

### ISSUE THREAD

**Issue by matu3ba** [alepez/vim-gtest#24]
setting up with
```lua
vim.g['my#variable'] = 'build/runTests' -- test binary location
---- gtest ----
map('n', ']t', [[<cmd>GTestNext<CR>]], opts)
map('n', '[t', [[<cmd>GTestPrev<CR>]], opts)
map('t', '<leader>tu', [[<cmd>GTestRunUnderCursor<CR>]], opts)
map('n', '<leader>tt', [[<cmd>GTestRun<CR>]], opts)
```

does not work as expected. For example test under cursor has no effect.

**Comment by matu3ba** [comment]
Looks like it is a configuration issue. My bad.

`:GTestRunUnderCursor` prints something, but breaks due to not finding file `./test`.

**Comment by alepez** [comment]
Thanks for the feedback. If you feel that documentation has to be improved, PRs are welcome!
