### ISSUE TITLE
A similar request for benchmark tools request.

### ISSUE THREAD

**Issue by hudengjunai** [alepez/vim-gtest#26]
Thanks for your vim-gest plugin. it's quite usefull in vim/c++ ide. recently. the [google-benchmarks](https://github.com/google/benchmark)is also wide used in benchmark code snippet and functions. and the mode is simillar to gtest. also Cmd/filter pattern.  So can you give a simple implimentation for vim-benchmarks plugin?

**Comment by alepez** [comment]
Hi @hudengjunai, thank you for appreciation. I'm currently working on [this project](https://github.com/alepez/provola) which will be the base (as a server) for a future vim plugin for testing with any framework (not just googletest). I'll take into account the possibility to also add google-benchmark and other benchmarks tool to this project. In the meanwhile, you can fork my `vim-gtest` project and slightly change it to work with gooogle-benchmarks.

**Comment by hudengjunai** [comment]
> Hi @hudengjunai, thank you for appreciation. I'm currently working on [this project](https://github.com/alepez/provola) which will be the base (as a server) for a future vim plugin for testing with any framework (not just googletest). I'll take into account the possibility to also add google-benchmark and other benchmarks tool to this project. In the meanwhile, you can fork my `vim-gtest` project and slightly change it to work with gooogle-benchmarks.

good. I am trying.
