### ISSUE TITLE
"clear" does not work when dispatch is using the job strategy 

### ISSUE THREAD

**Issue by bartlibert** [alepez/vim-gtest#27]
When running in a terminal and using the "job" strategy of vim-dispatch, the "clear" on this line fails: 
https://github.com/alepez/vim-gtest/blob/d3ea8b6ccdff56906a86843bdc45b9af4296c742/autoload/gtest.vim#L59

Because of that, the tests are never running. Just removing the "clear" fixes it.

The reason is that vim jobs don't use a shell, so clearing the shell fails, so clear return a non-zero error code.

**Comment by alepez** [comment]
I guess that clear is here for a reason. What about changing `&&` with `;`?

I mean:

```
 return "( clear ; " . l:cmd . ")" 
```

**Comment by bartlibert** [comment]
I guess it's there to clear some potential "startup output" when launching a new shell? No idea. 

But the good news: using ";" instead of "&&" works!
