### ISSUE TITLE
Feature request: custom dispatch function in `gtest#GTestRun()`

### ISSUE THREAD

**Issue by jiangyinzuo** [alepez/vim-gtest#32]
In [autoload/gtest.vim](https://github.com/alepez/vim-gtest/blob/d950713b3d5aadea34ab1af338eeb13421e3cb2e/autoload/gtest.vim#L223), could we add a custom dispatch function in `gtest#GTestRun()` to support arbitrary runners?

**Comment by alepez** [comment]
Hi @jiangyinzuo. Thanks for your suggestion. I'm not using this plugin anymore and I even forgot how to correctly write vimscript :smile: (I wrote this 9 years ago)

So, if you have any good idea, I'll be glad to accept your PR.

What I think about it: if new async runners plugins (like vim-dispatch, neomake...) have been created in the last 9 years, we can add them [here](https://github.com/alepez/vim-gtest/blob/d950713b3d5aadea34ab1af338eeb13421e3cb2e/autoload/gtest.vim#L223). 

For arbitrary runners, a configuration variable can be added, like the existing one `g:gtest#gtest_command`. It can be something like `g:gtest#gtest_runner`.
