### ISSUE TITLE
Make usable with vim-dispatch instead of vimux

### ISSUE THREAD

**Issue by bbannier** [alepez/vim-gtest#6]
[vim-dispatch](https://github.com/tpope/vim-dispatch) seems to provide most of the functionality needed from vimux, but also comes with fallbacks for screen or in the absence of a multiplexer.

**Comment by alepez** [comment]
Thank you, this is a good idea. I'll try this asap.

**Comment by alepez** [comment]
From v1.1.0 vim-gtest uses `:Make` if vim-dispatch is installed
