### ISSUE TITLE
Setup tests binary with projectionist

### ISSUE THREAD

**Issue by pdavydov108** [alepez/vim-gtest#9]
Hello, thanks for this interesting plugin, this is what I was looking for a long time! I have a question, is it possible to set `g:gtest#gtest_command` in `.projections.json` file, like those used by Tim Pope's [vim-projectionist](https://github.com/tpope/vim-projectionist) plugin? I have several projects that I work on, and setting gtest_command manually each time is boring, it would be nice just to add it to `.prjoections.json` per project, or even to be able to set a test file for some group of paths or sources in project.

**Comment by alepez** [comment]
Thank you @pdavydov108, this is an useful feature. I'll implement this asap. Or if you want to write a patch, feel free to submit a pull request.

**Comment by pdavydov108** [comment]
@alepez Sorry for late reply, I started looking for a way to do it, but I don't have much time now..

**Comment by alepez** [comment]
Can you provide an example of the `.prjoections.json` with settings for
vim-gtest?

Il giorno gio 10 mar 2016 alle ore 09:57 Pavel Davydov <
notifications@github.com> ha scritto:

**Comment by pdavydov108** [comment]
Well, in my opinion, it would be perfect to have something like this:

```
{
  "src/proj1/*.cpp": {
    "gtest_file": "tests/proj1_tests.cpp"
  },
  "src/proj2/tool1.cpp": {
    "gtest_file": "tests/tool1_tests.cpp"
  },
  "src/*.cpp": {
    "gtest_file": "tests/{}.cpp"
  }
}
```

This way it would be possible to provide a very flexible configuration, even to set a custom path to test file for every cpp. What do you think?
p.s. I stripped all other settings out of it. AFAIK, projectionist plugin can do all the work required to reconstruct paths here, we just have to query it somehow...
